### ISSUE TITLE
Why this Project???

### ISSUE THREAD

**Issue by mumli516** [chatchai-khuntichot/Flutter-with-T-Heatmap-AI-for-Thai#1]
This Project has literally nothing in it except for a image selection intent and a http request.

**Comment by chatchai-khuntichot** [comment]
[cid:a6f7199b-d526-4f4e-9468-03e6e13312ff]

There may be a problem with images that should be responded from the AI for Thai server.
________________________________
จาก: mumli516 <notifications@github.com>
ส่ง: 7 สิงหาคม 2563 5:36
ถึง: chatchai-khuntichot/Flutter-with-T-Heatmap-AI-for-Thai <Flutter-with-T-Heatmap-AI-for-Thai@noreply.github.com>
สำเนาถึง: Subscribed <subscribed@noreply.github.com>
ชื่อเรื่อง: [chatchai-khuntichot/Flutter-with-T-Heatmap-AI-for-Thai] Why this Project??? (#1)


This Project has literally nothing in it except for a image selection intent and a http request.
